api:
  id: "19355699"

amazon-s3-sapi:
  host: "amazon-s3-sapi-a0y7fb.5sc6y6-1.usa-e2.cloudhub.io"
  base-path: "api"
  request_path: "file"
  client_id: "d84f6d53e3b043fb879455465949ed0b"
  client_secret: "4D7363A0350346738D51bF42D077E304"
  file_path: ""